# Generated by Django 4.2.4 on 2023-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_id', models.TextField()),
                ('name', models.TextField()),
                ('size', models.IntegerField()),
                ('prime_color', models.TextField()),
                ('second_color', models.TextField()),
                ('shadow_color', models.TextField()),
                ('shadow_power', models.IntegerField()),
                ('orbit_size', models.IntegerField()),
                ('orbit_time', models.IntegerField()),
            ],
            options={
                'db_table': 'objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'object_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_id', models.TextField()),
            ],
            options={
                'db_table': 'panels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('value_length', models.IntegerField()),
            ],
            options={
                'db_table': 'panel_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('icon_path', models.TextField(blank=True, null=True)),
                ('prime_color', models.TextField(blank=True, null=True)),
                ('second_color', models.TextField(blank=True, null=True)),
                ('shadow_color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'systems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValueRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('img_src', models.TextField(blank=True, null=True)),
                ('color_a', models.TextField(blank=True, null=True)),
                ('color_b', models.TextField(blank=True, null=True)),
                ('color_c', models.TextField(blank=True, null=True)),
                ('h_color_a', models.TextField(blank=True, null=True)),
                ('h_color_b', models.TextField(blank=True, null=True)),
                ('h_color_c', models.TextField(blank=True, null=True)),
                ('close_button', models.TextField(blank=True, null=True)),
                ('extra_hrefs', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'value_row',
                'managed': False,
            },
        ),
    ]
